package cz.vutbr.fit.pdb.project.tables;
// Generated Dec 10, 2017 4:55:13 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;

import cz.vutbr.fit.pdb.project.model.TableBase;

/**
 * Parcela generated by hbm2java
 */
@Entity
@Table(name = "PARCELA")
public class Parcela extends TableBase implements java.io.Serializable {

	private String cislo;
	private Serializable geometrie;

	public Parcela() {
	}

	public Parcela(String cislo) {
		this.cislo = cislo;
	}

	public Parcela(String cislo, Serializable geometrie) {
		this.cislo = cislo;
		this.geometrie = geometrie;
	}

	@Id
	@Column(name = "CISLO", unique = true, nullable = false, length = 10)
	public String getCislo() {
		return this.cislo;
	}

	public void setCislo(String cislo) {
		this.cislo = cislo;
	}

	@Column(name = "GEOMETRIE")
	public Serializable getGeometrie() {
		return this.geometrie;
	}

	public void setGeometrie(Serializable geometrie) {
		this.geometrie = geometrie;
	}

}
