package cz.vutbr.fit.pdb.project.tables;
// Generated Nov 28, 2017 5:54:05 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Parcela generated by hbm2java
 */
@Entity
@Table(name = "PARCELA")
public class Parcela implements java.io.Serializable {

	private String cislo;
	private Serializable geometrie;

	public Parcela() {
	}

	public Parcela(String cislo) {
		this.cislo = cislo;
	}

	public Parcela(String cislo, Serializable geometrie) {
		this.cislo = cislo;
		this.geometrie = geometrie;
	}

	@Id

	@Column(name = "CISLO", unique = true, nullable = false, length = 10)
	public String getCislo() {
		return this.cislo;
	}

	public void setCislo(String cislo) {
		this.cislo = cislo;
	}

	@Column(name = "GEOMETRIE")
	public Serializable getGeometrie() {
		return this.geometrie;
	}

	public void setGeometrie(Serializable geometrie) {
		this.geometrie = geometrie;
	}

}
