package cz.vutbr.fit.pdb.project.tables;
// Generated Dec 10, 2017 4:55:13 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import cz.vutbr.fit.pdb.project.model.TableBase;

/**
 * Parkovani generated by hbm2java
 */
@Entity
@Table(name = "PARKOVANI")
public class Parkovani  extends TableBase implements java.io.Serializable {

	private BigDecimal idParkovani;
	private ParkovaciMisto parkovaciMisto;
	private Pobyt pobyt;
	private Date zacatek;
	private Date konec;

	public Parkovani() {
	}

	public Parkovani(BigDecimal idParkovani) {
		this.idParkovani = idParkovani;
	}

	public Parkovani(BigDecimal idParkovani, ParkovaciMisto parkovaciMisto, Pobyt pobyt, Date zacatek, Date konec) {
		this.idParkovani = idParkovani;
		this.parkovaciMisto = parkovaciMisto;
		this.pobyt = pobyt;
		this.zacatek = zacatek;
		this.konec = konec;
	}

	@Id

	@Column(name = "ID_PARKOVANI", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdParkovani() {
		return this.idParkovani;
	}

	public void setIdParkovani(BigDecimal idParkovani) {
		this.idParkovani = idParkovani;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MISTO_ID")
	public ParkovaciMisto getParkovaciMisto() {
		return this.parkovaciMisto;
	}

	public void setParkovaciMisto(ParkovaciMisto parkovaciMisto) {
		this.parkovaciMisto = parkovaciMisto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POBYT_ID")
	public Pobyt getPobyt() {
		return this.pobyt;
	}

	public void setPobyt(Pobyt pobyt) {
		this.pobyt = pobyt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ZACATEK", length = 7)
	public Date getZacatek() {
		return this.zacatek;
	}

	public void setZacatek(Date zacatek) {
		this.zacatek = zacatek;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "KONEC", length = 7)
	public Date getKonec() {
		return this.konec;
	}

	public void setKonec(Date konec) {
		this.konec = konec;
	}

}
