package cz.vutbr.fit.pdb.project.tables;
// Generated Dec 10, 2017 4:55:13 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.Long;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;

import cz.vutbr.fit.pdb.project.model.TableBase;
import cz.vutbr.fit.pdb.project.tables.entities.JGeometryType;

/**
 * ParkovaciMisto generated by hbm2java
 */
@Entity
@Table(name = "PARKOVACI_MISTO")
public class ParkovaciMisto extends TableBase implements java.io.Serializable {

	@Id
	@Column(name = "ID_MISTA", unique = true, nullable = false, precision = 22, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "parkovaci_misto_seq")
	@SequenceGenerator(name = "parkovaci_misto_seq", sequenceName = "parkovaci_misto_seq", allocationSize = 1, initialValue = 1)
	private Long idMista;
	@Column(name = "POZN")
	private String pozn;
	@Column(name = "GEO_MISTA")
	@Type(type = "JGeometryType")
	private JGeometryType geoMista;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parkovaciMisto")
	private Set<Parkovani> parkovanis = new HashSet<Parkovani>(0);

	public ParkovaciMisto() {
	}

	public ParkovaciMisto(Long idMista) {
		this.idMista = idMista;
	}

	public ParkovaciMisto(Long idMista, String pozn, JGeometryType geoMista, Set<Parkovani> parkovanis) {
		this.idMista = idMista;
		this.pozn = pozn;
		this.geoMista = geoMista;
		this.parkovanis = parkovanis;
	}

	public Long getIdMista() {
		return this.idMista;
	}

	public void setIdMista(Long idMista) {
		this.idMista = idMista;
	}

	public String getPozn() {
		return this.pozn;
	}

	public void setPozn(String pozn) {
		this.pozn = pozn;
	}

	public JGeometryType getGeoMista() {
		return this.geoMista;
	}

	public void setGeoMista(JGeometryType geoMista) {
		this.geoMista = geoMista;
	}

	public Set<Parkovani> getParkovanis() {
		return this.parkovanis;
	}

	public void setParkovanis(Set<Parkovani> parkovanis) {
		this.parkovanis = parkovanis;
	}

}
