package cz.vutbr.fit.pdb.project.tables;
// Generated Dec 10, 2017 4:55:13 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import cz.vutbr.fit.pdb.project.model.TableBase;

/**
 * Pobyt generated by hbm2java
 */
@Entity
@Table(name = "POBYT")
public class Pobyt  extends TableBase implements java.io.Serializable {

	private BigDecimal idPobyt;
	private Vjezd vjezd;
	private Vozidlo vozidlo;
	private Vyjezd vyjezd;
	private Date vjezd_1;
	private Date vyjezd_1;
	private Set<Parkovani> parkovanis = new HashSet<Parkovani>(0);

	public Pobyt() {
	}

	public Pobyt(BigDecimal idPobyt) {
		this.idPobyt = idPobyt;
	}

	public Pobyt(BigDecimal idPobyt, Vjezd vjezd, Vozidlo vozidlo, Vyjezd vyjezd, Date vjezd_1, Date vyjezd_1,
			Set<Parkovani> parkovanis) {
		this.idPobyt = idPobyt;
		this.vjezd = vjezd;
		this.vozidlo = vozidlo;
		this.vyjezd = vyjezd;
		this.vjezd_1 = vjezd_1;
		this.vyjezd_1 = vyjezd_1;
		this.parkovanis = parkovanis;
	}

	@Id

	@Column(name = "ID_POBYT", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdPobyt() {
		return this.idPobyt;
	}

	public void setIdPobyt(BigDecimal idPobyt) {
		this.idPobyt = idPobyt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VJEZD_ID")
	public Vjezd getVjezd() {
		return this.vjezd;
	}

	public void setVjezd(Vjezd vjezd) {
		this.vjezd = vjezd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AUTO_ID")
	public Vozidlo getVozidlo() {
		return this.vozidlo;
	}

	public void setVozidlo(Vozidlo vozidlo) {
		this.vozidlo = vozidlo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VYJEZD_ID")
	public Vyjezd getVyjezd() {
		return this.vyjezd;
	}

	public void setVyjezd(Vyjezd vyjezd) {
		this.vyjezd = vyjezd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VJEZD", length = 7)
	public Date getVjezd_1() {
		return this.vjezd_1;
	}

	public void setVjezd_1(Date vjezd_1) {
		this.vjezd_1 = vjezd_1;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VYJEZD", length = 7)
	public Date getVyjezd_1() {
		return this.vyjezd_1;
	}

	public void setVyjezd_1(Date vyjezd_1) {
		this.vyjezd_1 = vyjezd_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pobyt")
	public Set<Parkovani> getParkovanis() {
		return this.parkovanis;
	}

	public void setParkovanis(Set<Parkovani> parkovanis) {
		this.parkovanis = parkovanis;
	}

}
