package cz.vutbr.fit.pdb.project.tables;
// Generated Dec 10, 2017 4:55:13 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;

import cz.vutbr.fit.pdb.project.tables.entities.JGeometryType;

/**
 * Vjezd generated by hbm2java
 */
@Entity
@Table(name = "VJEZD")
public class Vjezd implements java.io.Serializable {

	private BigDecimal idVjezd;
	private JGeometryType geoVjezd;
	private Set<Pobyt> pobyts = new HashSet<Pobyt>(0);

	public Vjezd() {
	}

	public Vjezd(BigDecimal idVjezd) {
		this.idVjezd = idVjezd;
	}

	public Vjezd(BigDecimal idVjezd, JGeometryType geoVjezd, Set<Pobyt> pobyts) {
		this.idVjezd = idVjezd;
		this.geoVjezd = geoVjezd;
		this.pobyts = pobyts;
	}

	@Id

	@Column(name = "ID_VJEZD", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdVjezd() {
		return this.idVjezd;
	}

	public void setIdVjezd(BigDecimal idVjezd) {
		this.idVjezd = idVjezd;
	}

	@Column(name = "GEO_VJEZD")
	@Type(type = "JGeometryType")
	public JGeometryType getGeoVjezd() {
		return this.geoVjezd;
	}

	public void setGeoVjezd(JGeometryType geoVjezd) {
		this.geoVjezd = geoVjezd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vjezd")
	public Set<Pobyt> getPobyts() {
		return this.pobyts;
	}

	public void setPobyts(Set<Pobyt> pobyts) {
		this.pobyts = pobyts;
	}

}
