package cz.vutbr.fit.pdb.project.tables;
// Generated Nov 28, 2017 5:54:05 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vjezd generated by hbm2java
 */
@Entity
@Table(name = "VJEZD")
public class Vjezd implements java.io.Serializable {

	private BigDecimal idVjezd;
	private Set<Pobyt> pobyts = new HashSet<Pobyt>(0);

	public Vjezd() {
	}

	public Vjezd(BigDecimal idVjezd) {
		this.idVjezd = idVjezd;
	}

	public Vjezd(BigDecimal idVjezd, Set<Pobyt> pobyts) {
		this.idVjezd = idVjezd;
		this.pobyts = pobyts;
	}

	@Id

	@Column(name = "ID_VJEZD", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdVjezd() {
		return this.idVjezd;
	}

	public void setIdVjezd(BigDecimal idVjezd) {
		this.idVjezd = idVjezd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vjezd")
	public Set<Pobyt> getPobyts() {
		return this.pobyts;
	}

	public void setPobyts(Set<Pobyt> pobyts) {
		this.pobyts = pobyts;
	}

}
